name: Build and Deploy Franklin Site

on:
  push:
    branches:
      - source

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Install dependencies
        run: julia --project -e 'using Pkg; Pkg.instantiate()'
      
      - name: Install highlight.js 💡
        run: julia --project -e 'using NodeJS; run(`$(npm_cmd()) install highlight.js`)'

      - name: Build site 🔨
        run: julia --project -e 'using Franklin; using NodeJS; Franklin.optimize(clear=true)'

      # --- 修正箇所 ---
      - name: Edit sitemap.xml 📝
        run: |
          # 1. 認証ファイルを削除
          perl -i -p0e 's|<url>\s*<loc>https://akita-kosuke.github.io/google99f26b157d2cc0de\.html</loc>.*?<priority>.*?</priority>\s*</url>||gs' __site/sitemap.xml
          
          # 2. "/index.html" を "/" (スラッシュ) に置換して、ディレクトリ形式にする
          perl -i -pe 's|/index.html|/|g' __site/sitemap.xml

      - name: Copy verification file 🔑
        run: cp google99f26b157d2cc0de.html __site/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: __site
          token: ${{ secrets.GITHUB_TOKEN }}